### ISSUE TITLE
Segmentation fault in vpf_mocks

### ISSUE THREAD

**Issue by gbeltzmo** [manodeep/Corrfunc#150]
vpf_mocks produces a segmentation fault when not given a centers file (i.e. randoms are needed and given). After running with valgrind, I get an "Invalid read of size 8" on line 441 of countspheres_mocks_impl_double.c. 

Here is what's on that line:
   xcen = xran[itry];

I put an assert on itry to make sure that itry < sizeof(xran), and it is. The seg fault does not seem to happen when I provide a centers file.

**Comment by manodeep** [comment]
That logic with `need_centers` and `need_randoms` is quite flaky at best. Passing the centers file has always worked, while passing the randoms file has failed *at least sometimes* (depending on the size of the largest sphere). 

What happens if you add `assert(itry < Nran)` before the [xcen=xran[itry];](https://github.com/manodeep/Corrfunc/blob/master/mocks/vpf_mocks/countspheres_mocks_impl.c.src#L435) line?

I am surprised that the `itry < sizeof(xran)` passed - I would have expected `sizeof(xran)` to return `sizeof(DOUBLE *) == 8`.

**Comment by gbeltzmo** [comment]
Adam just fixed it! Something was just being freed too early. On line 405
in counts_spheres_mocks_impl.c.src the free statements for xran, yran, and
zran should be moved to within the if statement on line 538. Doing that
seems to fix it.

**Comment by manodeep** [comment]
@gbeltzmo Will you please send in a PR with the fix?

**Comment by manodeep** [comment]
Sorry @gbeltzmo -- re-opening the issue. Let's keep this issue open until the fix lands in the `master` branch. Thanks again!

**Comment by manodeep** [comment]
Fix was in #168

**Comment by manodeep** [comment]
The fix has now on master
